version: '3.3'
services:
   laravel:
        build:
            context: .
            dockerfile: docker/fpm/Dockerfile
        ports:
            - "9000"
        working_dir: /var/www
        volumes:
            - '.:/var/www'
        networks:
            - appnet
        restart: unless-stopped
        depends_on:
            - mongodb
   mongodb:
        env_file:
          - .env.sample
        image: 'mongo'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_DB_DATABASE}'
        volumes:
          - 'mongodata:/data/db'
        networks:
            - appnet
        ports:
            - '${MONGO_DB_PORT}'
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh mongodb:'${MONGO_DB_PORT}' --quiet
            retries: 3
            timeout: 10s
   nginx:
        restart: unless-stopped
        image: nginx:alpine
        volumes:
            - './docker/fpm/conf.d/:/etc/nginx/conf.d/'
        volumes_from:
            - mongodb
            - laravel
        ports:
            - "8000:80"
            - "4443:443"
        networks:
          - appnet
networks:
   appnet:
        driver: bridge
volumes:
   mongodata:
        driver: local
        external: false
