version: '3'
services:
    laravel:
        build: .
        ports:
            - '8080:8000'
        volumes:
            - '.:/var/www/html'
        networks:
            - appnet
        depends_on:
            - mongodb
    mongodb:
        image: 'mongo'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '' # Set DB username
            MONGO_INITDB_ROOT_PASSWORD: '' # Set DB password
        volumes:
          - 'mongodata:/data/db'
        networks:
            - appnet
        ports:
            - '27017:27017'
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017 --quiet
            retries: 3
            timeout: 10s
networks:
    appnet:
        driver: bridge
volumes:
    mongodata:
        driver: local       
        external: false
