version: '3.3'
services:
   laravel:
        env_file:
            - .env.testing
        container_name: fllr_laravel_test
        build:
            context: .
            dockerfile: docker/testing/Dockerfile
        ports:
            - "8000:8000"
        networks:
            - appnet
        depends_on:
            - mongodb
   mongodb:
        container_name: fllr_mongodb_test
        env_file:
          - .env.testing
        image: 'mongo'
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: '${MONGO_DB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGO_DB_PASSWORD}'
            MONGO_INITDB_DATABASE: '${MONGO_DB_DATABASE}'
        networks:
            - appnet
        ports:
            - '${MONGO_DB_PORT}:${MONGO_DB_PORT}'
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh mongodb:'${MONGO_DB_PORT}' --quiet
            retries: 3
            timeout: 10s
        logging:
            driver: none
networks:
   appnet:
        driver: bridge
